### PR TITLE
feat: Add BasePopover.tsx

### PR DESCRIPTION
**Pull request by SilviaZeta**
## Description
As it says on the tin.

## Dependency changes
No

## Testing
No

## Documentation
No

## Migrations (if applicable)
No

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New migrations have been committed
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If appropriate, I have bumped any version numbers

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
Could you provide a list of places where this will be used for me?

**Review by ChasNelson1990 — CHANGES_REQUESTED** [review]
Please add an example.

Also, do we really need to call everything BaseXXX?

**Comment by ChasNelson1990** [comment]
> Could you provide a list of places where this will be used for me?

We use popovers in CURATE and ANNOTATE as well as for trusted services in DOMINATE - this looks like it's specific to DOMINATE, no?

**Comment by SilviaZeta** [comment]
> Could you provide a list of places where this will be used for me?

To start with i'll use this to build the trusted service and plugin button toolbars, but we use popovers in lots of other places.

**Comment by SilviaZeta** [comment]
> Please add an example.

Ok
> 
> Also, do we really need to call everything BaseXXX?

No :-) though i like having the same prefix for reusable components.

**Review by cooper667 — APPROVED** [review]

**Comment by cooper667** [comment]
If you're bored you could change it to use the new `IconButton` but I don't really mind

**Review by philipjackson — APPROVED** [review]

**Pull request merged**
