### PR TITLE
feat: unify the two dialog(ue) and card components BREAKING CHANGE

### PR DESCRIPTION
**Pull request by ChasNelson1990**
## Description

Unfortunately we have accidentally kept old versions of the new Storybook-friendly components. So when I updated the Storybook-friendly Dialogue component and updated a downstream repo I saw none of my changes as the actually exported component was an old version hanging around. @ChrisBaidoo and I have a plan to slowly unify diverging components and have put in plans to prevent it happening any more.

In the mean time, this is step one: merging the Dialog (now Dialogue) and Card components (a required child). This is a breaking change as some optional props have changed name.

Note for @ChrisBaidoo we seem to be using two spellings for Dialogue. I have gone for the new(?) spelling of "Dialogue" where I can but we should be very careful of this.

## Checklist:

- [x] I have read the gliff.ai Contribution Guide.
- [x] I have requested to **pull a branch** and not from main.
- [x] I have checked all commit message styles match the requested structure.
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have performed a self-review of my own code.
- [x] I have assigned **3 or less** reviewers.
- [x] New and existing unit tests pass locally with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] My changes generate no new warnings.
- [x] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
@ChrisBaidoo - check out the percy visual change (old example page). I think this may be a problem that cascades down to other repos?

**Comment by ChrisBaidoo** [comment]
> @ChrisBaidoo - check out the percy visual change (old example page). I think this may be a problem that cascades down to other repos?

It looks like the Datagrid component renders a card inside it?

**Comment by ChasNelson1990** [comment]
> It looks like the Datagrid component renders a card inside it?

Half(?) fixed - if you set internalPadding to true it solves the big card inside the main body problem but seems to break the dialog header spacing?

**Comment by ChrisBaidoo** [comment]
Screenshot 2022-07-18 at 15 58 39

Are we removing the margin around the title?

**Comment by ChasNelson1990** [comment]
> Are we removing the margin around the title?

I didn't touch how the dialogue or card do their padding at all... so this is a bit bizarre that it's an issue when moving the old example page to the storybook components... given the storybook components seem fine. Have you maybe flipped the default for a prop somewhere? I would imagine this will cascade as an issue in downstream repos too?

**Comment by ChasNelson1990** [comment]
@ChrisBaidoo could it be this line: https://github.com/gliff-ai/style/blob/615a3a4bccb8295431d3269b49990434d553f3a3/src/components/Card/Card.tsx#L120
If `internalPadding` is `boolean` then can it ever actually be `null`?

**Comment by SilviaZeta** [comment]
I'd don't see why we'd need new components, but can we keep the old ones in for now, given that the other repos still use those? The old `Card` for example has the extra prop `backgroundColor`.

**Comment by ChasNelson1990** [comment]
> I don't see why we'd need new components, but can we keep the old ones in for now, given that the other repos still use those? The old `Card` for example has the extra prop `backgroundColor`. This so that we don't have to update all of the components at once if we need to make a change in style.

Yea, they shouldn't really have been duplicated in the first place as it leads to (and has led to) divergence. This is an attempt to start the reunification process before that divergence gets too bad.
Updating all the components at once after they have all been updated is just going to cause massive issues as we will essentially be replacing every component at once!

With regard to the specific backgroundColour option - I presume that has been removed to ensure style consistency and is a deprecated feature that should no longer be used? @joshuajames-smith and @ChrisBaidoo should be able to help answer that though.

**Comment by SilviaZeta** [comment]
makes sense! No,`backgroundColour` is not deprecated. I've noticed it was missing, because it is one of the last things I've added in style: ZOO has a `Card` with a light-grey background.

**Comment by ChasNelson1990** [comment]
Ah, so this is the divergence problem @SilviaZeta - could you add it back please?

**Review by ChrisBaidoo — APPROVED** [review]

**Pull request merged**
