### PR TITLE
feat: add 'show strokes as pixels' icon

### PR DESCRIPTION
**Pull request by joshuajames-smith**
## Description

Created and added a new icon for 'show strokes as pixels' tool to differentiate icons between the duplication for 'convert spline to paintbrush'.

Added .svg file. Added icon into icon.ts.

relates #457 (annotate)

## Documentation

@philhallbio when icon is implemented, tool documentation will need updated

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New migrations have been committed
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If appropriate, I have bumped any version numbers

### CODE REVIEW

**Comment by joshuajames-smith** [comment]
VSC picked up on a commit the last PR I did (in a different branch) which is already merged?

**Comment by cooper667** [comment]
Reckon you're up to adding it to examples too?

**Comment by ChasNelson1990** [comment]
> VSC picked up on a commit the last PR I did (in a different branch) which is already merged?

You need to rebase - did we discuss this?

**Comment by joshuajames-smith** [comment]
> Reckon you're up to adding it to examples too?

Haha open to trying and find out how well I can pick it up!

**Comment by cooper667** [comment]
Oh they get automatically added to examples anyway!

and you approved it!

**Review by cooper667 — DISMISSED** [review]

**Comment by cooper667** [comment]
> > VSC picked up on a commit the last PR I did (in a different branch) which is already merged?
> 
> You need to rebase - did we discuss this?

It's not too bad as squash is the only option in this repo so will sort itself out

**Review by ChasNelson1990 — APPROVED** [review]

**Review by cooper667 — APPROVED** [review]

**Pull request merged**
